/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { PrismaJsonValue } from "./prismaJsonValue";

export interface DefaultSelectionPrisma36ResponsePayload {
  createdAt: string;
  data: PrismaJsonValue;
  formId: string;
  id: string;
  updatedAt: string;
}
