/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */

export interface DefaultSelectionPrisma36FormPayload {
  active: boolean;
  authorId: string;
  createdAt: string;
  id: string;
  title: string;
  updatedAt: string;
}
