/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */

export type EnumsSucessScreen =
  (typeof EnumsSucessScreen)[keyof typeof EnumsSucessScreen];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnumsSucessScreen = {
  STANDART: "STANDART",
  CUSTOM: "CUSTOM",
} as const;
