/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */

export type GetUserDataById200 = {
  createdAt: string;
  email: string;
  emailVerified: string;
  id: string;
  image: string;
  name: string;
  updatedAt: string;
};
