/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */

/**
 * From https://github.com/sindresorhus/type-fest/
Matches a JSON array.
 */
export interface JsonArray { [key: string]: unknown }
