/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { JsonObject } from './jsonObject';
import type { JsonArray } from './jsonArray';

/**
 * From https://github.com/sindresorhus/type-fest/
Matches any valid JSON value.
 * @nullable
 */
export type JsonValue = string | number | boolean | JsonObject | JsonArray | null;
