/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { N24ResultDefaultSelectionPrisma24FormPayloadSuccessScreen } from "./n24ResultDefaultSelectionPrisma24FormPayloadSuccessScreen";

export interface N24ResultDefaultSelectionPrisma24FormPayload {
  active: boolean;
  authorId: string;
  createdAt: string;
  /** @nullable */
  customUrlError: string | null;
  /** @nullable */
  customUrlSuccess: string | null;
  emailNotification: boolean;
  emailNotificationMails: string[];
  /** @nullable */
  folder: string | null;
  id: string;
  keys: string[];
  spamProtected: boolean;
  /** @nullable */
  successScreen: N24ResultDefaultSelectionPrisma24FormPayloadSuccessScreen;
  title: string;
  updatedAt: string;
}
