/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type NullableAny = {
  createdAt: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  emailVerified: string | null;
  id: string;
  /** @nullable */
  image: string | null;
  /** @nullable */
  name: string | null;
  updatedAt: string;
} | null;
