/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { PickFormExcludeKeyofFormIdOrCreatedAtOrUpdatedAtOrAuthorId } from "./pickFormExcludeKeyofFormIdOrCreatedAtOrUpdatedAtOrAuthorId";

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitFormIdOrCreatedAtOrUpdatedAtOrAuthorId =
  PickFormExcludeKeyofFormIdOrCreatedAtOrUpdatedAtOrAuthorId;
