/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { PartialOmitFormIdOrCreatedAtOrUpdatedAtOrAuthorIdSuccessScreen } from './partialOmitFormIdOrCreatedAtOrUpdatedAtOrAuthorIdSuccessScreen';

/**
 * Make all properties in T optional
 */
export interface PartialOmitFormIdOrCreatedAtOrUpdatedAtOrAuthorId {
  active?: boolean;
  /** @nullable */
  customUrlError?: string | null;
  /** @nullable */
  customUrlSuccess?: string | null;
  emailNotification?: boolean;
  emailNotificationMails?: string[];
  /** @nullable */
  folder?: string | null;
  spamProtected?: boolean;
  /** @nullable */
  successScreen?: PartialOmitFormIdOrCreatedAtOrUpdatedAtOrAuthorIdSuccessScreen;
  title?: string;
}
