/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsSucessScreen } from "./_36EnumsSucessScreen";

/**
 * Make all properties in T optional
 */
export interface PartialForm {
  active?: boolean;
  authorId?: string;
  createdAt?: string;
  customUrlError?: string;
  customUrlSuccess?: string;
  emailNotification?: boolean;
  emailNotificationMails?: string[];
  folder?: string;
  id?: string;
  spamProtected?: boolean;
  successScreen?: _36EnumsSucessScreen;
  title?: string;
  updatedAt?: string;
}
