/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { PartialFormSuccessScreen } from "./partialFormSuccessScreen";

/**
 * Make all properties in T optional
 */
export interface PartialForm {
  active?: boolean;
  authorId?: string;
  createdAt?: string;
  /** @nullable */
  customUrlError?: string | null;
  /** @nullable */
  customUrlSuccess?: string | null;
  emailNotification?: boolean;
  emailNotificationMails?: string[];
  /** @nullable */
  folder?: string | null;
  id?: string;
  keys?: string[];
  spamProtected?: boolean;
  /** @nullable */
  successScreen?: PartialFormSuccessScreen;
  title?: string;
  updatedAt?: string;
}
