/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { PrismaJsonObject } from "./prismaJsonObject";
import type { PrismaJsonArray } from "./prismaJsonArray";

/**
 * From https://github.com/sindresorhus/type-fest/
Matches any valid JSON value.
 * @nullable
 */
export type PrismaJsonValue =
  | string
  | number
  | boolean
  | PrismaJsonObject
  | PrismaJsonArray
  | null;
