/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */
import type { ResultDefaultSelectionPrismaResponsePayload } from "./resultDefaultSelectionPrismaResponsePayload";

/**
 * Model Response
 */
export type Response = ResultDefaultSelectionPrismaResponsePayload;
