/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * platforma-backend
 * Platforma Backend Package
 * OpenAPI spec version: 1.0.0
 */

export enum SucessScreen {
  STANDART = "STANDART",
  CUSTOM = "CUSTOM",
}
