name: Platforma CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 21
      uses: actions/setup-node@v2
      with:
        node-version: 21.x
    - run: npm i
    - run: npm run build
    - run: pm2 start pm2-deploy.json